apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maestro-operator
rules:
  - apiGroups: ["maestro.dev"]
    resources: ["streamapplications"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["maestro.dev"]
    resources: ["streamapplications/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
