apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-operator
  labels:
    app: maestro-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro-operator
  template:
    metadata:
      labels:
        app: maestro-operator
    spec:
      serviceAccountName: maestro-operator
      containers:
        - name: operator
          image: maestro-operator:local
          imagePullPolicy: IfNotPresent
